### ISSUE TITLE
node-sass needs to be upgraded to work with Ubuntu 18.04

### ISSUE THREAD

**Issue by beejunk** [jkk/shinkgs#172]
## Issue
It looks like `node-sass` needs to be upgraded in order to work with Ubuntu 18.04.
## Steps to reproduce

1. On an Ubuntu 18.04 machine, clone the _shingkgs_ repository.
2. Run `yarn`
3. Run `yarn start`.
You should now get output that looks like this:
```bash
yarn run v1.6.0
$ yarn run build-sass
$ node-sass --include-path='node_modules' src/css/index.scss src/index.css
/home/brian/Projects/shinkgs/node_modules/node-sass/lib/binding.js:13
      throw new Error(errors.unsupportedEnvironment());
      ^

Error: Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (57)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.5.2
    at module.exports (/home/brian/Projects/shinkgs/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/home/brian/Projects/shinkgs/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/brian/Projects/shinkgs/node_modules/node-sass/bin/node-sass:11:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
## Solution
Upgrading `node-sass` to to versoin 4.9.0 solves this problems.

**Comment by jkk** [comment]
hey @beejunk! Pull down the latest master; I pushed a fix for this in commit d920202

**Comment by beejunk** [comment]
Hah, I just saw that you did this! Okay, closing down this issue...

**Comment by jkk** [comment]
no worries, thanks for the detailed report! 🙂
